### ISSUE TITLE
Implements device_state_attributes

### ISSUE THREAD

**Issue by stu1811** [LorenzoVasi/HA_mdadm#2]
Running core-2022.3.7 I see the following warning in the logs...

`Entity binary_sensor.raid_status_dev_md0 (<class 'custom_components.mdadm_state.binary_sensor.mdadm'>) implements device_state_attributes. Please report it to the custom component author.`

**Comment by LorenzoVasi** [comment]
Hi mate,
I have reconised the warning; its caused by an update of HAcore, where the def `device_state_attributes` has been deprecated and replaced with `extra_state_attributes`

I'll fix it, thanks for report 🙂
