### ISSUE TITLE
No longer showing in HACS

### ISSUE THREAD

**Issue by jasdmeyer** [LorenzoVasi/HA_mdadm#3]
Hello,

I can no longer find this project in the HACS repository.  I installed manually, but when I did a "check configuration," in the Developer tools tab, no result was returned.  I didn't see anything in the logs either.  On HA 2023.11 with Docker.

Thanks

**Comment by LorenzoVasi** [comment]
Hi,
I'm sorry for the problem you're having
Can you make some screenshots of problem? what do you mean with "no result"? I tried to replicate with a new instance of  HA2023.11v and i don't find any problems...
Could you describe to me step by step what you did?
Could you also send me your docker compose?
PS. Sorry, you're right, the following repository is no longer present on HACS, now i'll add a method for integrate it with HACS

**Comment by jasdmeyer** [comment]
I updated to the latest version and was able to get the integration working.  Thanks!

**Comment by LorenzoVasi** [comment]
Okay, perfect! 👍 I'll close the issue :)
