### ISSUE TITLE
Yaml check failed

### ISSUE THREAD

**Issue by jlrosssc** [LorenzoVasi/HA_mdadm#5]
Not sure if this is an issue or not.  I'm running HA on Docker.  Will this work on Docker?  If not, that's the issue, not the integration.

My RAID is /dev/md125, 126 and 127 but to test, I'm only referencing device: md125 but it's not passing the YAML check.

**Comment by LorenzoVasi** [comment]
Hola chicooo
Yes, it should work with Docker too because the `/proc/mdstat` file might be shared with the container...
I think there is a problem with the implementation of the integration
How did you install the integration? Can you send me your Configuration.yaml?
Send me some screenshots and the yaml check error

**Comment by jlrosssc** [comment]
Well..... oddly enough it's working now. Previously, it never technically had an error, the YAML config check just kept running for minutes and never completed. When I commented the mdadm lines out, it worked fine. When I tried again to take the screen shot just now it worked. I added all 3 drives and am getting data for each. Is there a way of getting the detailed information like state? Appologies for bugging you. This tool is exactly what I've been looking for. Thank you. On May 9, 2024, at 8:11 AM, LorenzoVasi ***@***.***> wrote: Hola chicooo Yes, it should work with Docker too because the /proc/mdstat file might be shared with the container... I think there is a problem with the implementation of the integration How did you install the integration? Can you send me your Configuration.yaml? Send me some screenshots and the yaml check error — Reply to this email directly, view it on GitHub , or unsubscribe . You are receiving this because you authored the thread. Message ID: ***@***.***>

**Comment by LorenzoVasi** [comment]
Perfect!
All details are passed tò HA as attribute of the entity
Let me know if you have other problemsss
Byebye
